main:
    project: 'self_supervised_graph'
    dataset: 'paloalto'
    version: 'none'
    disable_wandb: True
paths:
    home: /home/buechner/zuern/
    package: /home/buechner/zuern/self-supervised-graph/
    dataroot: /data2/buechner/autograph/
    dataroot_urbanlanegraph: /home/buechner/zuern/urbanlanegraph-dataset-dev/
    checkpoints: /home/buechner/zuern/self-supervised-graph/checkpoints/
    config_name: exp-11-01-23/* # preprocessed/city_name or preprocessed/*
preprocessing:
    gt_pointwise: True
    sampling_method: poisson
    num_node_samples: 2000
    edge_proposal_method: random  # triangular or random
    N_interp: 5
    k_waypoints: 1
    visualize: False
    ego_regressor_num_channels: 4
    augment: False
model:
    dataparallel: True
    device: cuda
    batch_size: 4
    batch_size_reg: 384
    lr: 1e-4
    beta_lo: 0.9
    beta_hi: 0.999
    num_epochs: 1000
    gnn_depth: 1
    # lane_mpnn
    map_feat_dim: 64
    node_dim: 16
    edge_dim: 32
    msg_dim: 32
    edge_geo_dim: 16
    # end_of_archs
    in_layers: rgb,sdf,angle  # which inputs to use for LaneGNN map encoder
    loader_workers: 16
    weight_decay: 1e-4 #0.0001
    ignore_low_scores: False
    checkpoint:
