main:
    project: 'self_supervised_graph'
    dataset: 'paloalto'
    version: 'none'
    disable_wandb: True
paths:
    home: /home/zuern/
    package: /home/zuern/self-supervised-graph/
    dataroot: /data/autograph/
    dataroot_av2: /data/argoverse2/motion-forecasting/
    checkpoints: /home/zuern/self-supervised-graph/checkpoints/
    config_name: exp-05-01-23/* # preprocessed/city_name or preprocessed/*
preprocessing:
    gt_pointwise: True
    sampling_method: poisson
    num_node_samples: 2000
    edge_proposal_method: random  # triangular or random
    N_interp: 5
    k_waypoints: 1
    visualize: False
    ego_regressor_num_channels: 4
    augment: False
model:
    dataparallel: False
    device: cuda
    batch_size: 1
    batch_size_reg: 16
    lr: 1e-3
    beta_lo: 0.9
    beta_hi: 0.999
    num_epochs: 10000
    gnn_depth: 2      # default: 1, 2 works
    # lane_mpnn
    map_feat_dim: 32  # default 64
    node_dim: 16
    edge_dim: 32
    msg_dim: 32
    edge_geo_dim: 16
    # end_of_archs
    in_layers: rgb,sdf,angle  # which inputs to use for LaneGNN map encoder (i.e. rgb | rgb,sdf | rgb,sdf,angle)
    loader_workers: 4
    weight_decay: 1e-4
    ignore_low_scores: False
    checkpoint:
