main:
    project: 'self_supervised_graph'
    dataset: 'paloalto'
    version: 'none'
    disable_wandb: True
paths:
    home: /home/zuern/
    package: /home/zuern/self-supervised-graph/
    dataroot: /data/self-supervised-graph/
    dataroot_av2: /data/argoverse2/motion-forecasting/
    checkpoints: /home/zuern/self-supervised-graph/checkpoints/
    split: train
    config_name: av2  # av2 or ind
preprocessing:
    gt_pointwise: True
    sampling_method: poisson
    num_node_samples: 2000
    edge_proposal_method: triangular  # triangular or random
    N_interp: 5
    k_waypoints: 1
    visualize: False
    ego_regressor_num_channels: 4
model:
    dataparallel: True
    device: cuda
    batch_size: 1
    lr: 1e-3
    beta_lo: 0.9
    beta_hi: 0.999
    num_epochs: 10000
    gnn_depth: 6      # default: 3
    # lane_mpnn
    map_feat_dim: 64
    node_dim: 16
    edge_dim: 32
    msg_dim: 32
    edge_geo_dim: 16
    # end_of_archs
    in_channels: 3  # number of channels of image
    loader_workers: 0
    weight_decay: 1e-4 #0.0001
    ignore_low_scores: False
    checkpoint:

